### ISSUE TITLE
ieduplicates: issue with variable formats

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/ietoolkit#103]
When a variable in Stata has a different format than the one that is saved in excel, the commands throws an error saying observations were deleted.

For example, one you have a date variable, it is saved as a string in the excel report, but is a number in Stata, so the command can't match observations. Same happens for labeled variables and missing values. For now, I think the best solution is to make variables that cause this errors strings, but we should find a way to fix this or at least make the help file informative about this possiblity.

**Comment by luizaandrade** [comment]
@kbjarkefur the solution I found for this problem when I was creating the reports was to first convert the variables to string, then create the report. Do you think there's a more efficient way to do this?

**Comment by kbjarkefur** [comment]
Is it this error message that you get: 

> One or several observations in the Excel report are no longer found in the data set.

I agree that what you suggest is a good solution. To *tostring()* before generating the report, and to *tostring()* the variables before merging with the report. I only see one issue, we do not want to return the data set with any modifications to the variables. So we need to be able to revert this. 

The solutions is probably to make a clone of the variable under a new name. Then the last thing we do is clone it back. Also, I think this error (if it is the error I quoted above) can not be caused in variables listed in *keepvar()* only in *uniquevar()*, so that might reduce the work we need to do.

```
*Create a tempvar clone and order it next to the original var 
*this will have to be repeated over all uniquevars
tempvar iedup1
clonevar `iedup1' = uniquevar1
order `iedup1', after(uniquevar1)

tostring uniquevar1 , replace //we should probably use *force* here as well

*generate report, merge back the report etc.

* before returning the data set delete the var we modified and replace it with the clone
drop uniquevar1
clonevar uniquevar1 = `iedup1'
order uniquevar1 , after(`iedup1')
```

What do you think?

**Comment by luizaandrade** [comment]
I cannot reproduce this error. I've managed to include both a date variable and a labelled factor without problems, so I will close this issue and we can come back to this if we ever come across this error again.
