### ISSUE TITLE
ieduplicates: allow more than one id variable

### ISSUE THREAD

**Issue by LeonardoViotti** [worldbank/ietoolkit#113]

**Comment by kbjarkefur** [comment]
I have always been skeptical to multiple ID variables. The only time I think it is justified is in longitudinal data sets such as panel data or time series. But this command is for raw data that is almost always collected in one time period at the time.

Most data science literature strongly recommends that only one ID variable is used, so I think I would like to keep ieduplicates promoting that practice, but I would like to hear about why your project team has decided to use multiple ID variables. I might be missing an important exception.

And it is not too difficult to make one variable out of two using for example `concat()` (use `tostring` first if numerical) and separate them with an underscore or something. 

Let me know what you think!

**Comment by bbdaniels** [comment]
Various types of surveys require multiples (person within household, doctor within facility, type of case presentation within doctor in medical vignettes) and require that all these variables be accessible at each level for merging  purposes. So usually you will have multiples and creating a "single" one is an extra step (there are some commands that require it anyway such as xtset) and so the "Stata-like" practice imo is to allow multiples (as in collapse)

**Comment by kbjarkefur** [comment]
I agree that it might be the "Stata-like" practice among many Stata users and I think that is relevant, however, many Stata practices are archaic and not always desirable to follow. Imo, and according to most (if not all) literature outside the Stata world, thinks this is not a good practice. 

And I think the team behind Stata does not agree with its users. Collapse is not focusing on ID variables. It can, for example, be used to get the mean age for males that like the color blue. And neither gender nor favorite color in this example are ID vars. Commands that test for uniquely and fully identifying ID variables, like isid, also allow multiple variables as it is a tool to figure out what identifies the data set. However, the Stata commands that expect an ID variable already checked and verified, like xtset or tsset, do expect that data sets have one ID variable. So the "Stata-like" practice the way Stata was intended seems to differ from the "Stata-like" practice among many of its users.

And let me clarify, I do think that multiple ID vars are ok so that one can merge clinic data to patients using the clinic ID. But I do think that each data set should have one uniquely and fully identifying variable for the unit of observation in that data set. So even if there is clinic ID in a doctor data set the doctor ID should be uniquely and fully identifying by itself. I think this extra step is well worth doing.

**Comment by luizaandrade** [comment]
I used Leo's profile to create that issue because I couldn't access GitHub then. I have a listing data set that tracks which households are using which plots. So neither plots nor households uniquely identify observations. I agree that it would be straightforward to create a unique ID in this case, but I think this is a relatively common issue, and though I agree that it's usually best practice to have one unique ID, I also think there are cases when creating an additional variable adds an unnecessary step.

My suggestions would be to create an option like "multidvarsok". We can throw a message saying it's not best practice, but still allow users to override the default.

**Comment by kbjarkefur** [comment]
After call with @luizaandrade, we decided to put label **low priority**. 

While multiple ID variables can be justified, it will require a re-writing of this command for how to do ID var corrections on multiple ID vars. And for cases when there is multiple ID vars the workaround would be to concatenate the ID vars to one unique var. The only problem with this is that corrections will not make sense to do through **ieduplicates**, but the main feature of the command still works as intended.

If someone in the future have time to re-write the command to also be able to do corrections on multiple ID vars data sets, that would be great! Feel free to fork and submit your implementation in a pull request!

**Comment by kbjarkefur** [comment]
Aurelie provided a use case for **ieduplicates** that I really liked that convinced me that we should allow for multiple variables.

She uses it for testing for enumerators instead of filling in a second form just went in to an already submitted form and changed the ID variable to the another respondent and then submit that again.

She currently test for this using the start time instead of ID variables. There is a small chance that exactly two interviews started at the same time, but in those rare cases, manual inspections will quickly tell if that was fraud or coincidence.

If we allow for multiple variables you can elaborate on such kind of tests. The problem of using **ieduplicates** to correct for multiple variable still stands. It is possible, but might require some major re-writing of the command. The solution in the first step could be to allow for multiple IDs but disable the correction function when multiple IDs are used. I know that some people using the command prefers to correct manually anyways.

Not an urgent priority, but I think we should do that eventually.

**Comment by luizaandrade** [comment]
I'm not sure I see how that implies in using more than one ID. For that test, wouldn't we only the starttime as an ID variable? If we don't want to enable changes, we could simply add duplicates times as a test in iehfc.

**Comment by kbjarkefur** [comment]
Good point. I was thinking that one could also use other ID vars to do the same test, and did not think that start time is the only variable ever needed for this test as it can never be edited.

Nevertheless, I do think that disabling the ID variable correction feature when using multiple ID variables counters one of my main arguments against the original request in this issue.

**Comment by kbjarkefur** [comment]
This command was moved to [iefieldkit](https://github.com/worldbank/iefieldkit) and the discussion regarding this issue will be continued in that repo.
