### ISSUE TITLE
create housekeeping command called ietoolkit

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#124]
Team-Lupe has a nice addition to make sure that calls to SSC to install user-written commands are only done if needed, see https://github.com/worldbank/AFG-TUP/commit/62471a78d7fdfac049500fa49cc52755642aa01d. I like this approach. We should perhaps make it standard in the master do-file iefolder creates.

But as in the case of ietoolkit they cannot use the name ietoolkit as there is no command with that name. Should we create a command that does just do stuff like outputting which version of ietoolkit is installed? the command `which` does something similar, but strangely they do not store it in a local or something.

Creating the command should be straightforward.

We should let whoever was the first to do this in Team-Lupe to make the edit to iefolder if we end up using it so he or she get contributions credits. I can prepare the code and send it so this should take no time. @eatorange, who was the first to suggest this in Team-Lupe?

**Comment by kbjarkefur** [comment]
ok, I will see if @luizaandrade have any objections to this, but otherwise I will create a branch and make the update to iefolder but then send that file to you so you can make the commit and get contirbution credit as soon as it has merged to the master branch. It is easier that I do the update and send it to you as iefolder.ado is a beast...

**Comment by eatorange** [comment]
That would be nice, as I still can't completely understand .ado file yet.

One thing I would like to comment is that, the codes currently confirming whether certain user-written commands exist (_cap which ...._) are executed **before** running `global_setup.do` file which sets custom ado file path. The problem is that, STATA will install user-written commands if it can't find them in default directory via `which` command, even if those commands actually exist in custom ado file paths.

One way we can solve is that, we can verify & install packages **AFTER** running global_setup.do file, thus STATA will install missing packages only after it searches custom ado-paths.

Another way is just leave it as it is. It is because even if STATA installs packages that are missing in default path but exist in custom ado-paths, STATA will always execute commands in the custom path first, because "`adopath++ (custom path)`" in the global_setup.do file let STATA prioritize the commands in the custom ado paths to default path.

**Comment by kbjarkefur** [comment]
I think it should be left as it is. It is good if it is installed even if it is not needed. Imagine someone who is less advanced Stata user that works in a project with someone like you who sets up custom paths sees a command used in that project, then goes to a different project and gets an error with exactly the same code. That would be confusing. 

It is true that it could be small differences as custom paths guarantees the exact same version, but any version is better than no version.

**Comment by luizaandrade** [comment]
This sounds great, @kbjarkefur and @eatorange! Please go ahead with the update to iefolder.

**Comment by kbjarkefur** [comment]
I think the `issue-124-ietoolkit-command` is ready to be merged, but we can wait until we publish a new version in case we come up with something else to put in the **ietoolkit** command.

I think this is a cool usage of it. Where you can force an update of the package if the version installed is too old.

```
cap ietoolkit
if "`r(version)'" == "" {
   *ietoolkit not installed, install it
   ssc install ietoolkit
}
else if `r(version)' < 5.0 {
   ietoolkit version too old, install the latest version
   ssc install ietoolkit , replace
 }
```

**Comment by kbjarkefur** [comment]
will close issue when update is published on SSC

**Comment by luizaandrade** [comment]
Published
