### ISSUE TITLE
iebaltab helpfile

### ISSUE THREAD

**Issue by SaoriIwa** [worldbank/ietoolkit#168]
Help file link to display_options does not work. 
(line 22 )  {it: {help iebaltab##display:display_options} might be
{it: {help iebaltab##displayoptions:display_options}

**Comment by kbjarkefur** [comment]
Thanks for reporting this! And you are right! That is what it is supposed to be! 

I could do this myself, but do you want to submit this edit yourself so that you get [contribution credits](https://github.com/worldbank/ietoolkit/graphs/contributors)? If so, create a PR to the _develop_ branch for this. I am happy to help if you have any questions on how to do that.

**Comment by kbjarkefur** [comment]
Issue is fixed. Issue will be closed once this update is published on SSC!
