### ISSUE TITLE
iebaltab : Order of the difference 

### ISSUE THREAD

**Issue by escandethomas** [worldbank/ietoolkit#178]
It would be great if we could have the mean difference as being (2) - (1) / (3) - (1) and (3) - (2). As (1) is usually the control group, I think it makes conceptually more sense to have treatment - control than the opposite to have a positive result when treatment is effective.

**Comment by kbjarkefur** [comment]
That's a very good point! I completely agree, and do not know why it isn't like that already. Thanks for bringing this up!

If this command would not already have been published I would definitely do as you suggest. But since that is not the case I want to think about it and discuss this with @luizaandrade and @bbdaniels . The problem is if someone already is using this for a table, and make a reference to a number, ex. -1.8, in the text, updates the command, and now that number is 1.8.

A compromise would be to add what you are suggesting as an option, but I think your suggestion should be the default, and the option to switch this feels like a patchwork kind of solution that we might end up regretting later. :confused:

**Comment by kbjarkefur** [comment]
This is solved in version `v7.0` by introducing the command `control()`. That indicates one group as control and test all other groups against it, and then flips the sign so positive difference means that treatment has a higher value than control.
