### ISSUE TITLE
ieduplicates: list variables that are different

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/ietoolkit#180]
Add a column in iedupreport with a list of all variables that are different across surveys with the same ID. So, for example, if it's only endtime or submissiondate, we don't need to go open the data set to know what's going on.

**Comment by kbjarkefur** [comment]
That is what **iecompdup** is doing, but I understand that you want to skip the manual step. Since the code already exist in **iecompdup** and since that command returns that list that should not be too difficult to implement as we allow **ietoolkit** commands to depend on other commands in the kit. 

The only issue I see are if there are three or more observations that have the same duplicated ID. I guess the result in that column could be an error message telling the user to investigate that specific case manually. Or could we solve those cases in a meaningful way?

**Comment by luizaandrade** [comment]
I was not thinking of doing everything that iecompdup is doing, but just listing the names of the variables in the report. So we can solve the cases that are more obvious without running iecompdup, which I think should still be a separate functionality. Does that make sense?

**Comment by kbjarkefur** [comment]
Ok, so lets list variables when that are differ if there are only two observations when the same ID, and if the list is shorter than 10 variables (is that a good number, I do not want to list 1000s of variables), and in all other cases recommend using `iecompdup`?

**Comment by kbjarkefur** [comment]
This command was moved to [iefieldkit](https://github.com/worldbank/iefieldkit) and the discussion regarding this issue will be continued in that repo.
