### ISSUE TITLE
ieduplicates: issue with string newID

### ISSUE THREAD

**Issue by MRuzzante** [worldbank/ietoolkit#182]
I ran into the following error every day I was using `ieduplicates`:
> The ID varaible hhid is numeric but newID has thes non-numeric values: . Update newID to only contain numeric values or see option tostringok.

The issue was that the `newID` column in the Excel file was exported as string every time I ran the code. Manually changing `newID` to number in the Excel would avoid this.

I solved it by adding `destring newID, replace` in line 698 of the ado file, and now it's working well. Credits to @luizaandrade! :)

**Comment by kbjarkefur** [comment]
@MRuzzante , as always, thanks for feedback!

Can you copy and paste a few lines of code before and a few lines of code after the location where you added `destring newID, replace`? I am not sure I am looking at the right place even though you were very specific. 😕 

We can add an option so that this can be specified when running the command. I am thinking two commands. `importdestring()` and `importtostring()` that takes variable names of variables in the report as argument and `destring` or `tostring` after importing. Makes sense?

**Comment by MRuzzante** [comment]
Here it goes:
```
			/******************
				Section 7.2.1
				ID var in original file is string. Either
				newID was imported as string or the variable
				is made string. Easy.
			******************/
			destring newID, replace
			
			* If ID variable is string in original Stata file
			if substr("`type_0'",1,3) == "str" {
```

Yes, that sounds like a reasonable solution to me!

**Comment by kbjarkefur** [comment]
This command was moved to [iefieldkit](https://github.com/worldbank/iefieldkit) and the discussion regarding this issue will be continued in that repo.
