### ISSUE TITLE
[ieddtab]: T1_mean not returned

### ISSUE THREAD

**Issue by akartapanis** [worldbank/ietoolkit#237]
Hi,

I was looking around to see if there is a library that provides nice DiD univariate tables and came across ieddtabResults. I want the output to look a bit different so I tried access the returned matrix and noticed that instead of return T0_mean and T1_mean, you return T0_mean twice.

Upon further inspection, the issue seems to be on this line of the ado script:
``local colnames `2ndDiff_cols' `1stDiff_C_cols' `1stDiff_T_cols' `basicMean_C0_cols' `basicMean_T0_cols' `basicMean_C1_cols' `basicMean_T0_cols'``

The last term should be basicMean_T1_cols and not basicMean_T0_cols.

I hope this helps.

**Comment by kbjarkefur** [comment]
Thanks this is really great feedback and great catch. We apologize for this bug.

I have not looked into the code, but it seems as if you have solved this bug yourself. If you want contribution credit for fixing it, feel free to create a fork and send a PR and I will review and accept. I can also do it myself if you prefer. Let me know.

Do you like the feature with the returned matrix? We piloted that for this command, and are now working on implementing that in more commands. We have not heard from anyone we do not already know who has used this feature, so it would be interesting to hear any other feedback you might have when working with the return matrix.

**Comment by kbjarkefur** [comment]
Fixed in ad6d8743ef28d9e7b9ca4c867ec2dd29e43d4332 just like @akartapanis suggested! Thanks again!

Checked results. Error did not affect the estimates in the table, it just made one estimate in the result matrix inaccessible. This value was not displayed in the result window table or the standard LaTeX and therefore it was not found earlier. 

I have also set up a proper test file in c8fd043cf9ebcebbfc401983018eb8435098f451 that now test that all values in the matrix is accessible.

**Comment by kbjarkefur** [comment]
Since results were not incorrect I de-escalated to a minor bug, meaning that we will immediately go through the full checklist of publishing to SSC. We will soon publish a new version, and this fix will be included then. 

Here are one way to install the updates already now before they are published to SSC: https://github.com/worldbank/ietoolkit/blob/master/admin/test-instructions.md

**Comment by akartapanis** [comment]
> Thanks this is really great feedback and great catch. We apologize for this bug.
> 
> I have not looked into the code, but it seems as if you have solved this bug yourself. If you want contribution credit for fixing it, feel free to create a fork and send a PR and I will review and accept. I can also do it myself if you prefer. Let me know.
> 
> Do you like the feature with the returned matrix? We piloted that for this command, and are now working on implementing that in more commands. We have not heard from anyone we do not already know who has used this feature, so it would be interesting to hear any other feedback you might have when working with the return matrix.

Thanks for taking care of this @kbjarkefur. I should had mentioned that the results are not affected, and it was just a matrix issue; sorry for that.

Returning the matrix is definitely useful! Given that the matrix provides more details than the default output, it allows me to format the output the way I want. For example in my field we care about showing mean values for treated observations pre and post treatment and the change there, and then the same for the control group and then finally have a column presenting the difference in difference result. Your default output does not present this format, but all of the info is in the return matrix which is awesome.

**Comment by kbjarkefur** [comment]
Awesome! 

No worries about not mentioning the results. The `major bug` label is for when we fear someone will use the command and get incorrect results without noticing it. Then we prioritize this task until a new version is on SSC. But that is our method of triage, we are just grateful that you reported the bug, and on top of that gave us the solution.

If you end up writing code that turn the result matrix into a latex table according to the preference of your field, would you mind sharing it? Eventually we want a page similar to this: https://worldbank.github.io/Stata-IE-Visual-Library/ but instead of examples of Stata code for graphs, we want a library of example code for how to turn the result matrix of `ieddtab` and `iebaltab` to different flavors of tables. You will of course be credited.
