### ISSUE TITLE
[iebaltab] - Allow to show BOTH the inter-group difference AND pvalue in an extra column or below 

### ISSUE THREAD

**Issue by idagri** [worldbank/ietoolkit#295]
Hi! Thanks for the very useful program!
Just as I'm working to produce a balance test table, I've been trying to get a table where the last column is the difference and under (or next to) it one could see the actual pval (not just the start) or st dev to have a more comprehensive comparison. 
I've scavenged the help file, but I don't believe it is possible, it's either difference OR pvalue with the ``pttest`` option!

Here's what I have in mind graphically to make it easier to see:
(I moved the pvalue column in Excel manually and added the difference to show the desired result) 

![image](https://user-images.githubusercontent.com/33915653/196880158-633a4c23-f8f0-4150-b12b-07a61cda301c.png)

Let me know if you'd consider adding it :)

**Comment by idagri** [comment]
renamed more consistently

**Comment by kbjarkefur** [comment]
Great to hear that you find this command useful! `iebaltab` had at one point grown so much from what it initially was that it was next to impossible to add new feature in its original structure. Therefore, we have spent the time we have for this Stata package on re-writing the whole command. This work is almost done and you can follow it here: https://github.com/worldbank/ietoolkit/pull/288

In the new structure, it will be much easier to add new features like this. You can see all issues that are a part of this re-write or waiting for this re-write to be done here: https://github.com/worldbank/ietoolkit/issues?q=is%3Aopen+is%3Aissue+label%3A%22iebaltab+re-write%22

One of those issues is suggesting something similar to what you are suggesting. See here: https://github.com/worldbank/ietoolkit/issues/293. We will allow multiple stats but those stats will probably be introduced on multiple rows instead of multiple columns. Although I am adding the suggestion to add multiple stats in extra columns, and this will be discussed when we are ready to implement this. Feel free to contribute to the discussion if you think it is important that there is an option to add more stats in extra columns.

**Comment by kbjarkefur** [comment]
Since this issue is quite similar to the other issue, I will close this issue so that the discussion is in a single place. Please do not interpret this as you opening an issue was not welcomed. We truly appreciate that. We just want to make sure we keep the feature request neatly organized.

**Comment by RRMaximiliano** [comment]
Just adding to @kbjarkefur's response and to your other issue. You can also use the same tweak we did for the subgroups. In this case, you can use merge after computing the difference and the run iebaltab again with the pttest, and then you can exported as you pleased. For example:

![image](https://user-images.githubusercontent.com/7269831/197038169-e6b114c0-c713-4c7f-aec6-3aff3d7cf81a.png)

**Code:**
```
* Load data
  set seed 0231894
  sysuse auto, clear

* random treatment variable
  gen rand = runiform()
  gen treatment = (rand >= 0.5)

* iebaltab example
  // First by foreign == 0 
  preserve
    iebaltab price mpg if foreign == 0, grpvar(treatment) ///
      order (1 0) control(1) browse onerow tblnonote
      
    tempfile first
    save `first'
  restore
  
  iebaltab price mpg if foreign == 0, grpvar(treatment) ///
    order (1 0) control(1) browse onerow tblnonote pttest
  
  rename v4 v5
  drop v1-v3
  
  merge using `first'
  drop _merge
  order v5, last

```

**Comment by idagri** [comment]
That's true, again, thanks a lot! I think working through the browse option for now is going to help me automate quite a few things, thanks a lot for these suggestions, I really appreciate such prompt feeback!! @RRMaximiliano @kbjarkefur 
😄
