### ISSUE TITLE
[iebaltab] - Sub-group comparisons to append to the same table

### ISSUE THREAD

**Issue by idagri** [worldbank/ietoolkit#296]
Hi!

It seems that there is no "append" option, but it would be great if it was possible to add subgroup balance tables to the same table :)

E.g. let's say an intervention was performed in several different classes, which have been appended into the same ``dta`` file and I want to do the comparison for the first 1/3 of the sample from the first class, then for the second, etc.:

```
iebaltab y `controls' if class == "Biology" , ... savetex(title) replace
iebaltab y `controls' if class == "Economics", ... savetex(title) append
iebaltab y `controls' if class == "English" , ... savetex(title) append

```
To get something like this:

![image](https://user-images.githubusercontent.com/33915653/196881549-53638e6e-2c5e-40fa-880e-5688647fb87d.png)

Maybe I missed something :)

Thanks in advance!

**Comment by kbjarkefur** [comment]
Thank you for this suggestion as well! My answer here will be very similar to my answer in https://github.com/worldbank/ietoolkit/issues/295. This is also waiting for the re-write (which have taken an embarrassingly long time to do). 

This is suggested in the issue https://github.com/worldbank/ietoolkit/issues/98, so I will close this issue. Again only to organize our own discussion. Your issue is a good reminder we need to get the re-write version of the door, and it helps making sure that an append option should be one of our first priorities.

**Comment by idagri** [comment]
I see, I get it, looking forward to the revamped release! @kbjarkefur 

And thanks a lot @RRMaximiliano, it didn't occur to me to do append via browse, this can be the solution for the time being, since I don't mind doing the code this way ones, but I am strongly against any sort of manual editing of tables after the export :)

Thank you both for the replies!

Best,
Ida
