### ISSUE TITLE
iebaltab : issue with escape charcter

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/ietoolkit#65]
when a label as a $ inside a word, like in **Fanta$tic**. Then the escape character does not work. When numbers follows like **$2000** then it works.

I have only tested this in the table notes. Not in any other label

**Comment by kbjarkefur** [comment]
Or maybe this happens already in the option **tblnote()** when specifying the command. anyways, let's look into this when we have time. This is a very minor bug

**Comment by luizaandrade** [comment]
Commit 1efd35a83fd2a84665860d14ebca67060c01cf01 partially addresses it. However, it only fixes the issue if the sign is only used in variables labels. Since this is probably the most common occurrence, it should work until we find a final fix. But possibly the fix will have to be to check if they are ever used in labels and just tell people to take them off, and maybe allow it to be used in the notes.

**Comment by kbjarkefur** [comment]
Closing this issue for now. Raise new issues for any specific examples. There are some base cases that still cause but none of them are likely to be ever uses, for example, a $ followed by a letter with no space. But that is unlikely as it is usually followed by number, space or punctuation.

We will fix specific cases that people actually encounters.
