### ISSUE TITLE
Description of "folder" option is missing in "syntax' category

### ISSUE THREAD

**Issue by eatorange** [worldbank/ietoolkit#9]
It seems that in “ieduplicates” helpfile, the description of “folder” option is missing under “Syntax” category (There is description of “folder” option under “Options” category below, but not in “Syntax” category).

**Comment by kbjarkefur** [comment]
Thank you for catching this @eatorange ! I have corrected this in the `develop` branch and it will be reflected in the next version of **ietoolkit**. Since it is not a critical bug I will not create a separate version just for this.

I will keep this issue open until this update is reflected on the SSC server.

Thanks again!
